-- 003_reset_auto_increment.sql

ALTER TABLE Roles AUTO_INCREMENT = 0;
ALTER TABLE Users AUTO_INCREMENT = 0;
ALTER TABLE StudentGroups AUTO_INCREMENT = 0;
ALTER TABLE Students AUTO_INCREMENT = 0;
ALTER TABLE Teachers AUTO_INCREMENT = 0;
ALTER TABLE Subjects AUTO_INCREMENT = 0;
ALTER TABLE ClassTimes AUTO_INCREMENT = 0;
ALTER TABLE Schedule AUTO_INCREMENT = 0;
ALTER TABLE Tasks AUTO_INCREMENT = 0;